
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ads-recommendation-system
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/[PROJECT-ID]/ads-recommendation
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: [YOUR_PROJECT_ID]
